### ISSUE TITLE
Actor and Object mapping are redundants

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/repository-doctrine#10]
Currently, `Object` can be an `Actor`. Having both is very confusing. What should we do about this @xabbuh ?

**Comment by xabbuh** [comment]
I agree that this is not really nice, but in terms of being able to effectively query the database through an LRS front-end I don't see another solution that wouldn't make that part harder to implement (and also be as efficient in terms of queries) as it is right now. Do you have an alternative implementation in mind?

**Comment by Lctrs** [comment]
I don't really know.

Alternative to this are not legion. Either we remove the `Actor` mapping class and centralize everything in the `Object` class.

Or we split the `Object` class into all its existing childs. We can maybe use the `discriminatorMap` feature from Doctrine ?

**Comment by xabbuh** [comment]
> Alternative to this are not legion. Either we remove the `Actor` mapping class and centralize everything in the `Object` class.

Which means that we would need to be extra careful when constructing a statement based on the stored data as we cannot be sure anymore that the returned row actually represents an actor. Meaning that debugging might become quite hard.

> Or we split the `Object` class into all its existing childs. We can maybe use the `discriminatorMap` feature from Doctrine ?

Usually, using mapping inheritance with Doctrine is not recommended and should be avoided. I would rather not like to switch to it.

**Comment by Lctrs** [comment]
> Which means that we would need to be extra careful when constructing a statement based on the stored data as we cannot be sure anymore that the returned row actually represents an actor. Meaning that debugging might become quite hard.

Since we are constructing the mapped objects from the model, we are certain to get back an actor object, no ?

**Comment by Lctrs** [comment]
Looking at the [LRS implementation from ADL](https://github.com/adlnet/ADL_LRS) (Python/Django), they appear to add a field for every child type a relation with an `Object` can be.
