### ISSUE TITLE
Proposal changes to the Mapped Repositories Interfaces

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/repository-doctrine#13]
Currently, their names can be confusing with our "real" repositories interfaces defined in `php-xapi/repository-api` (by real, I mean the ones that we'll use in the LrsBundle).

So, I propose to mark them as internal and change their suffix part to `Storage` (ex. : `StatementStorage` for `XApi\Repository\Doctrine\Repository\Mapping\StatementRepository`).

WDYT @xabbuh ?

**Comment by xabbuh** [comment]
But in terms of Doctrine these classes are indeed repositories. So maybe we could remove the `Mapping` namespace and change the class name to `XApi\Repository\Doctrine\Repository\MappingStatementRepository`. What do you think?

**Comment by Lctrs** [comment]
The implementations are, our interfaces are not (even if they are only meant to be implemented by a Doctrine Repository).

I don't find `MappingStatementRepository` to be very explicit. :/

**Comment by xabbuh** [comment]
> The implementations are, our interfaces are not (even if they are only meant to be implemented by a Doctrine Repository).

Fair point. :) Please take a look at #17.
